package:
  name: esgf-config-parser
  version: {{ environ['VERSION'] }}

source:
  git_url: git://github.com/sterlingbaldwin/esgf-config-parser.git
  git_tag: {{ environ['TAG'] }}

build:
  noarch: python
  script: python setup.py install
  string: {{ environ['BUILD_NAME'] }}

about:
    home: https://github.com/sterlingbaldwin/esgf-config-parser
    summary: ESGConfigParser python library to parse ESGF INI files 

requirements:
  build:
    - python
    - setuptools
    - pip
  
  run:
    - python
    